name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: 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
        TARGET_REPO: ChelFannie/chelFannie.github.io.source
        TARGET_BRANCH: main
        BUILD_SCRIPT: yarn && yarn build
        BUILD_DIR: dosc/.vuepress/dist/
