name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: vuepress-deploy
      uses: ChelFannie/chelFannie.github.io@main
      env:
        ACCESS_TOKEN: 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
        TARGET_REPO: ChelFannie/chelFannie.github.io.source
        TARGET_BRANCH: main
        BUILD_SCRIPT: yarn && yarn build
        BUILD_DIR: dosc/.vuepress/dist/
